config/routes.rb
Rails.application.routes.draw do
    get 'todos', to: 'todos#index'
    get 'todos/new'
    get 'todos/list'
    post 'todos',to: 'todos#create'
    post 'todos/:id/complete', to: 'todos#complete', as:'complete_todo'
    get 'todos/:id', to: 'todos#show', as: 'todo'
    get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
    patch 'todos/:id', to: 'todos#update'
    delete 'todos/:id', to: 'todos#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
        @todos = Todo.all
    end

    def new
        @todo = Todo.new
    end

    def create
        @todo = Todo.new(todo_params)
        @todo.save
        redirect_to todos_path
    end

    def show
        @todo = Todo.find(params[:id])
    end

    def destroy
        @todo = Todo.find(params[:id])
        @todo.destroy
        redirect_to todos_path
    end

    def edit
        @todo = Todo.find(params[:id])
    end

     def update
        @todo = Todo.find(params[:id])
        @todo.update(todo_params)
        redirect_to todos_path
     end

     def complete
        @todo = Todo.find(params[:id])
          if @todo.completed == true
              @todo.completed = false
              @todo.save
              redirect_to todos_path
          else
              @todo.completed = true
              @todo.save
              redirect_to todos_path
          end
     end

     def list
         @todos = Todo.all
     end

private
    def todo_params
        params.require(:todo).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_menu.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <%= link_to 'Home', todos_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'List', todos_list_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'NEW', todos_new_path, class:"nav-link" %>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cyborg/bootstrap.min.css" rel="stylesheet" integrity="sha384-mtS696VnV9qeIoC8w/PrPoRzJ5gwydRVn0oQ9b+RJOPxE1Z1jXuuJcyeNxvNZhdx" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="padding-top:69px">     
    <%= render 'layouts/menu' %>
    <%= yield %>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <!-- popper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <!-- bootstrap -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <%= form_with(model: @todo, local: true) do |f| %>
                     <h4><%= f.label :title, "Description: " %></h4>
                     <%= f.text_area :description %>
                    <h4> <%= f.label :estado, "Completed? " %> <%= f.check_box :completed%></h4>
                     <%= f.submit "Save", class:'btn btn-primary' %>
                     <%= link_to 'Back', todos_path , class:'btn btn-danger' %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/todos/edit.html.erb
<h1>New Task</h1>
<%= render 'form', todo: @todo %>

app/views/todos/index.html.erb
<section class="container">
    <h1> ToDo List - Rails Exam G21</h1>
    <h3>Add a new task for your 'ToDo List'</h3>
    <p><%= link_to 'Add Here', todos_new_path, class: 'btn btn-primary' %></p>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <% @todos.each do |todo| %>
                <div class="card">
                    <div class="card-body">
                        <h2>Description: <%= todo.description %> </h2>
                        <h4>Status: <%= todo.completed %></h4>
                        <%= link_to 'Show', todo %>
                        <strong>  |  </strong>
                        <%= link_to 'Edit', edit_todo_path(todo) %>
                        <strong>  |  </strong>
                        <%= link_to 'Delete', todo, method: :delete, data: { confirm: "This action can't be undo" },class:'btn btn-danger' %>
                        <strong>  |  </strong>
                        <%= link_to 'Complete', complete_todo_path(todo), method: :post, class:'btn btn-primary' %>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/todos/list.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
        <h2>Complete Task</h2>
    <% @todos.each do |t| %>
        <% if t.completed == true %>
          <p><%= t.description %></p>
        <% end %>
    <% end %>
    </div>
    <div class="col-6">
        <h2>Incomplete task</h2>
        <% @todos.each do |i| %>
            <% if i.completed == false %>
              <p><%= i.description %></p>
            <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<h1>New Task</h1>
<%= render 'form', todo: @todo %>

app/views/todos/show.html.erb
<h1>SHOW</h1>
<h2><strong>Content:</strong>
  <%= @todo.description %>
</h2>
<h3><strong>Status:</strong>
  <%= @todo.completed %>
</h3>

<p>
    <%= link_to 'Edit', edit_todo_path(@todo), class:'btn btn-primary' %>
    <strong>||</strong>
    <%= link_to 'Back', todos_path , class:'btn btn-danger' %></p>